/*****************************************************/
/* Auther : Eman Mohamed                             */
/* Date   : 15 August 2020                           */
/* Version: V01                                      */
/*****************************************************/
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SEVEN_SEGMENT_interface.h"
#include "SEVEN_SEGMENT_config.h"

void SEVEN_SEGMENT_voidInit(void)
{
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,OUTPUT_SPEED_2MHZ_PUSH_PULL);
		MGPIO_voidSetPinDirection(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,OUTPUT_SPEED_2MHZ_PUSH_PULL);

}
void SEVEN_SEGMENT_voidDisplay (u8 Copy_u8Number)
{	
	#if SEVEN_SEGMENT_TYPE == COMMON_CATHODE
	
			switch(Copy_u8Number)
			{
				case DISPLAY_0   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				
				case DISPLAY_1   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_2   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_3   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_4   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_5   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_6   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_7   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_8   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_9   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_DOT :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
				
			}
			
	#elif SEVEN_SEGMENT_TYPE == COMMON_ANODE
		
		switch(Copy_u8Number)
			{
				case DISPLAY_0   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
									
				
				case DISPLAY_1   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
				
				case DISPLAY_2   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
				case DISPLAY_3   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
				case DISPLAY_4   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_H);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
									///////////////////////////
				case DISPLAY_5   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_6   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_7   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_8   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_9   :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_HIGH);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_LOW);
									break ;
				case DISPLAY_DOT :
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINA,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINB,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINC,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PIND,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINE,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PINF,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_PING,GPIO_LOW);
									MGPIO_voidSetPinValue(SEVEN_SEGMENT_PORT,SEVEN_SEGMENT_DOT ,GPIO_HIGH);
									break ;
				
			}
#endif
	
		
}



